### ISSUE TITLE
Gitbugs.com is down, move to Github Pages?

### ISSUE THREAD

**Issue by hmert** [javierluraschi/gitbugs#3]
Hi,
I appreciate for this simple project. It's very usefull for me as a project manager when exporting issue's.

Please make it available again for the others :) I want contribute the project

**Comment by javierluraschi** [comment]
@hmert Sorry, this was a small hack I put together a while ago, which I happened to need today so I moved the page here to avoid paying for a domain name:

https://s3.amazonaws.com/gitbugs/index.html

Cheers!
